window.CHALLENGES = [
  {
    "id": 1,
    "name": "🌱 The Beginning",
    "description": "Your first step into the Linux world",
    "whatYouLearn": "Basic navigation commands: ls, pwd, and understanding the file system",
    "objective": "Learn basic navigation and file listing",
    "category": "Beginner",
    "difficulty": 1,
    "hint": "Use 'ls' to list files, 'pwd' to show your location",
    "tasks": [
      "Use `ls` to see all files and folders in the directory you are currently in.",
      "Use `pwd` to find the full path of the directory you are currently in.",
      "Use `ls -a` to display all files and folders, including hidden ones.",
      "Use `ls -l` to display files with details such as permissions, owner, size, and modification time."
    ],
    "flagHash": "02c8ea5f8593f8ccfebe1bd90c30337aa1d8f0a2a314a68fc96a353a570c46fe"
  },
  {
    "id": 2,
    "name": "🧭 Navigation Master",
    "description": "Learn to move around the filesystem",
    "whatYouLearn": "Master cd command, directory navigation, and path shortcuts (~, -, ..)",
    "objective": "Master cd command and directory navigation",
    "category": "Beginner",
    "difficulty": 1,
    "hint": "Use 'cd' to change directories, '..' to go up",
    "tasks": [
      "Use `cd ~` to move to your personal home directory.",
      "Use `cd /` to move to the Linux root directory, which is the top of the filesystem.",
      "Use `cd -` to return to the directory you were in just before the current one.",
      "Use `cd ..` to move up to the parent directory.",
      "Go to /var/log directory",
      "Go to /etc directory"
    ],
    "flagHash": "e22b8689b7db70f07aff233ac94e4412d19caee55b165a3bb47d3336e8158ebe"
  },
  {
    "id": 3,
    "name": "📁 Directory Creator",
    "description": "Create and manage directories",
    "whatYouLearn": "Create directories with mkdir, including nested directories with -p flag",
    "objective": "Learn mkdir and directory operations",
    "category": "Beginner",
    "difficulty": 1,
    "hint": "mkdir creates directories, -p creates parent directories",
    "tasks": [
      "Create a new folder named `projects` using `mkdir`.",
      "Create a new folder named `temp` using `mkdir`.",
      "Create the complete folder path `a/b/c`, including any parent folders that do not already exist.",
      "Create a folder named `My Documents`. Remember that spaces must be handled correctly in the command.",
      "Create three folders named `dir1`, `dir2`, and `dir3` with a single command."
    ],
    "flagHash": "7aeca651dbab55ab463579011ede7931d0307eec71a35df10498cbe61bb0ddab"
  },
  {
    "id": 4,
    "name": "📝 File Creation",
    "description": "Create files using different methods",
    "whatYouLearn": "Create files using touch, echo, cat and understanding redirection (>, >>)",
    "objective": "Learn touch, echo, and cat commands",
    "category": "Beginner",
    "difficulty": 1,
    "hint": "touch creates empty files, echo writes content",
    "tasks": [
      "Create an empty file named `notes.txt` using a suitable Linux command.",
      "Create three empty files named `file1.txt`, `file2.txt`, and `file3.txt` in one command.",
      "Create or overwrite `hello.txt` so that it contains the text `Hello World`.",
      "Add `Welcome to Linux` to the end of `hello.txt` without deleting its existing contents.",
      "Create file using cat redirection"
    ],
    "flagHash": "c57117cf75c898869c172b26997efb6602dfe284f02ab5f45f9062451587ecdc"
  },
  {
    "id": 5,
    "name": "👀 Viewing Files",
    "description": "View file contents in different ways",
    "whatYouLearn": "View files with cat, head, tail, less and real-time monitoring with tail -f",
    "objective": "Learn cat, head, tail, less commands",
    "category": "Beginner",
    "difficulty": 2,
    "hint": "head shows beginning, tail shows end of files",
    "tasks": [
      "Display all of the text inside `file.txt`.",
      "Display the first 10 lines of `log.txt`.",
      "Display the first 20 lines of `data.txt`.",
      "Display the last 10 lines of `syslog`.",
      "Display the last 50 lines of `syslog`.",
      "Watch `app.log` continuously so that new lines appear as they are added.",
      "Open `longfile.txt` one screen at a time so you can read a large file comfortably."
    ],
    "flagHash": "fd2b57572d38f104b62d37c62cddfe80484fff20926d6342094c19262fe0c7e0"
  },
  {
    "id": 6,
    "name": "📋 Copy & Move",
    "description": "Learn to copy and move files",
    "whatYouLearn": "Copy files with cp, move/rename with mv, and understanding recursive operations",
    "objective": "Master cp and mv commands",
    "category": "Beginner",
    "difficulty": 2,
    "hint": "cp copies, mv moves/renames files",
    "tasks": [
      "Create a copy of `file1.txt` named `file2.txt`.",
      "Copy every `.txt` file in the current directory into the `backup/` folder.",
      "Copy the entire `source_dir/` folder, including its contents, into `dest_dir/`.",
      "Copy with preservation of attributes",
      "Move `file.txt` into the `/tmp/` directory.",
      "Rename `oldname.txt` to `newname.txt`.",
      "Move multiple files to directory"
    ],
    "flagHash": "47194a11c8014124df61663de55225737b5494a086ed200978b0cfb746b07797"
  },
  {
    "id": 7,
    "name": "🗑️ Remove & Clean",
    "description": "Safely remove files and directories",
    "whatYouLearn": "Safely remove files with rm, remove directories with rmdir, and force deletion",
    "objective": "Learn rm, rmdir, and safe deletion",
    "category": "Beginner",
    "difficulty": 2,
    "hint": "rm removes files, rmdir removes empty directories",
    "tasks": [
      "Delete the file named `temp.log`.",
      "Delete `test.txt`, but make Linux ask you for confirmation first.",
      "Delete the empty folder named `empty`.",
      "Delete `old_folder` and everything inside it.",
      "Force-delete `force_delete.txt` without asking for confirmation.",
      "Delete `file1.txt`, `file2.txt`, and `file3.txt` with one command.",
      "Delete every file ending in `.tmp` in the current directory."
    ],
    "flagHash": "10e92cc229258a252e6bbf62c4d637fc082f8181c942bfe8fb9be04bd2fe33a3"
  },
  {
    "id": 8,
    "name": "🎯 Wildcards & Patterns",
    "description": "Use wildcards to work with multiple files",
    "whatYouLearn": "Use wildcards (*, ?, []) to match and manipulate multiple files efficiently",
    "objective": "Master *, ?, [] wildcards",
    "category": "Beginner",
    "difficulty": 2,
    "hint": "* matches any characters, ? matches single character",
    "tasks": [
      "Display every file whose name ends with `.txt`.",
      "Display files whose names begin with the letter `a`.",
      "Display filenames that contain exactly five characters.",
      "List files ending with .log or .txt",
      "Remove all .bak files",
      "Copy all .conf files to backup/",
      "List files with numbers 1-5"
    ],
    "flagHash": "ead833d205780a65f0b7f30c9e52f9a7a26d162b6cdd095515facf1b12bb620c"
  },
  {
    "id": 9,
    "name": "🔍 Search with grep",
    "description": "Search for patterns in files",
    "whatYouLearn": "Search text with grep, use options like -i, -r, -n, -w for powerful searches",
    "objective": "Learn grep and its options",
    "category": "Beginner",
    "difficulty": 3,
    "hint": "grep searches text, -i for case-insensitive",
    "tasks": [
      "Search `log.txt` and display lines containing the word `error`.",
      "Search for `warning` in `log.txt` without caring whether it is uppercase or lowercase.",
      "Search through the current directory and its subdirectories for the text `TODO`.",
      "Search `file.txt` for `pattern` and include the matching line numbers.",
      "Search `code.txt` for the complete word `main`, not words that merely contain `main`.",
      "Search for multiple patterns",
      "Search and show context (2 lines before/after)",
      "Search excluding certain files"
    ],
    "flagHash": "8b7f11fe4680abb2cee86f74cc5591b1ec27d89ac8ef633cb8217747316c0075"
  },
  {
    "id": 10,
    "name": "🔎 Find Files",
    "description": "Find files and directories",
    "whatYouLearn": "Use find command to search by name, type, size, and modification time",
    "objective": "Master find command",
    "category": "Beginner",
    "difficulty": 3,
    "hint": "find searches for files, -name for name pattern",
    "tasks": [
      "Use `find` to locate all `.txt` files starting from the current directory.",
      "Use `find` to locate files whose names contain `conf`.",
      "Use `find` to locate files that were modified within the last 7 days.",
      "Use `find` to locate files modified within the last 24 hours.",
      "Use `find` to locate files larger than 10 MB.",
      "Use `find` to locate files smaller than 1 KB.",
      "Use `find` to locate empty files and directories.",
      "Use `find` to locate directories only, excluding regular files.",
      "Find files and execute command"
    ],
    "flagHash": "b7db6127e5a7b5b993e7549f25cc63007d80c5919f7345391294da6330c448b8"
  },
  {
    "id": 11,
    "name": "🔐 File Permissions",
    "description": "Understanding and changing file permissions",
    "whatYouLearn": "Understanding rwx permissions, chmod with numbers and symbols, chown for ownership",
    "objective": "Learn chmod, chown, and permission basics",
    "category": "Intermediate",
    "difficulty": 3,
    "hint": "chmod with numbers: 755, 644, 400",
    "tasks": [
      "Change the permissions of `script.sh` so the file owner can execute it.",
      "Set `file.txt` to permission mode `755` (owner can read/write/execute; group and others can read/execute).",
      "Set `data.txt` to permission mode `644` (owner can read/write; everyone else can read).",
      "Set `secret.txt` so that only the owner has read permission.",
      "Set `private.txt` so that only the owner can read and write it.",
      "Add write permission for group",
      "Remove read permission for others",
      "Change file owner",
      "Change file group only",
      "Apply permissions recursively"
    ],
    "flagHash": "6f5a0e54c118618afc4607b321fea6df61a12f2a02ef2b227ee077af44e87d7e"
  },
  {
    "id": 12,
    "name": "🔗 Links & Shortcuts",
    "description": "Create and manage symbolic and hard links",
    "whatYouLearn": "Create symbolic links (shortcuts) with ln -s and understand hard links",
    "objective": "Understand soft and hard links",
    "category": "Intermediate",
    "difficulty": 3,
    "hint": "ln -s creates symbolic link",
    "tasks": [
      "Create symbolic link to file.txt",
      "Create symbolic link to directory",
      "Create hard link to data.txt",
      "List all links in directory",
      "Update existing symbolic link",
      "Find all symbolic links",
      "View link details"
    ],
    "flagHash": "0ac65a829495ef14e7f43053e1831c803dc6dc9c8f255416b86cdd66f6dcf5a3"
  },
  {
    "id": 13,
    "name": "📤 I/O Redirection",
    "description": "Redirect input and output",
    "whatYouLearn": "Redirect stdout with >, >>, stderr with 2>, and pipes | for chaining commands",
    "objective": "Master redirection and pipes",
    "category": "Intermediate",
    "difficulty": 3,
    "hint": "> overwrites, >> appends, 2> redirects errors",
    "tasks": [
      "Write output to file.txt",
      "Append output to file.txt",
      "Redirect error to error.log",
      "Redirect both stdout and stderr",
      "Use pipe to filter output",
      "Pipe multiple commands",
      "Use tee to split output",
      "Redirect to /dev/null"
    ],
    "flagHash": "c64a0c986af2d6814b979bc39618baa079b18201c73262460a67098e4215c2f7"
  },
  {
    "id": 14,
    "name": "📝 Text Processing",
    "description": "Advanced text manipulation tools",
    "whatYouLearn": "Use sed for search/replace, awk for column extraction, cut, sort, uniq, wc",
    "objective": "Master sed, awk, cut, sort, uniq",
    "category": "Intermediate",
    "difficulty": 4,
    "hint": "sed for replace, awk for columns",
    "tasks": [
      "Replace 'old' with 'new' in file",
      "Delete lines containing 'error'",
      "Print second column from data",
      "Print lines where column 3 > 100",
      "Cut first 10 characters",
      "Cut fields 1 and 3 with delimiter",
      "Sort file alphabetically",
      "Sort numerically descending",
      "Show unique lines",
      "Count occurrences of each line",
      "Count words, lines, characters",
      "Print specific line with sed"
    ],
    "flagHash": "56456b2624ed9a50752d7f0739fb8ff03d8f3044d28b0907bd9a073101d4598a"
  },
  {
    "id": 15,
    "name": "⚙️ Process Management",
    "description": "Monitor and control running processes",
    "whatYouLearn": "List processes with ps, monitor with top, kill processes, and manage jobs",
    "objective": "Learn ps, top, kill, and process signals",
    "category": "Intermediate",
    "difficulty": 4,
    "hint": "ps aux shows all processes, kill sends signals",
    "tasks": [
      "List all running processes",
      "Show process hierarchy",
      "List processes with CPU usage",
      "List processes by memory usage",
      "Show real-time process monitoring",
      "Kill process with PID 1234",
      "Force kill process",
      "Send SIGTERM signal",
      "Send SIGSTOP to pause process",
      "Send SIGCONT to resume process",
      "Start process in background",
      "Bring background job to foreground",
      "List background jobs"
    ],
    "flagHash": "ffa48e7ff8100a8b2396ac8286031810f288c50235a72c085df37e78833fe988"
  },
  {
    "id": 16,
    "name": "💻 System Information",
    "description": "Get system and hardware information",
    "whatYouLearn": "Check system info with uname, lscpu, free, df, and hardware details",
    "objective": "Learn system information commands",
    "category": "Intermediate",
    "difficulty": 4,
    "hint": "uname shows system info, free shows memory",
    "tasks": [
      "Show system information",
      "Show kernel version",
      "Show CPU information",
      "Show memory usage (human-readable)",
      "Show disk usage (human-readable)",
      "Show disk usage of current directory",
      "Show disk usage of all directories",
      "Show system uptime",
      "Show hostname",
      "Show system date and time",
      "Show who is logged in",
      "Show last system reboot"
    ],
    "flagHash": "da75b5f26c786c3f150cdcf7f1760a282a1c66c885c5f611ab42cc229b30120f"
  },
  {
    "id": 17,
    "name": "🌐 Network Basics",
    "description": "Basic network commands and diagnostics",
    "whatYouLearn": "Check connectivity with ping, view network interfaces with ip, check connections with ss",
    "objective": "Learn ping, ip, ss, netstat commands",
    "category": "Intermediate",
    "difficulty": 4,
    "hint": "ping checks connectivity, ip shows interfaces",
    "tasks": [
      "Ping google.com 4 times",
      "Check network interfaces",
      "Check network connections",
      "Show all listening ports",
      "Show routing table",
      "Trace route to google.com",
      "Check DNS resolution",
      "Show active connections with IPs",
      "Show network statistics",
      "Test specific port connectivity",
      "Show MAC address",
      "Check network bandwidth"
    ],
    "flagHash": "040ad0d4d2d5ad608d28b963aec7ba07863a3a26beb20abd3bf5de7b3e48e967"
  },
  {
    "id": 18,
    "name": "⚡ Advanced Processes",
    "description": "Advanced process control and monitoring",
    "whatYouLearn": "Process priorities, signals, background jobs, and process groups",
    "objective": "Master advanced process management",
    "category": "Intermediate",
    "difficulty": 5,
    "hint": "nice changes priority, nohup runs processes that survive logout",
    "tasks": [
      "Start process with low priority",
      "Start process with high priority",
      "Change priority of running process",
      "Run process that survives logout",
      "List all processes with nice values",
      "Send SIGUSR1 signal to process",
      "Display process tree",
      "Show process environment variables",
      "Limit process CPU time",
      "Limit process memory usage",
      "Show open files for process",
      "Show process memory maps"
    ],
    "flagHash": "11ff7aa7d5bd11f46854d3b86b078da84f86774c9a46720e50ec574ccd77ce3f"
  },
  {
    "id": 19,
    "name": "🌐 Network Configuration",
    "description": "Configure and manage network interfaces",
    "whatYouLearn": "Configure IP addresses, routes, DNS, and network interfaces",
    "objective": "Master network configuration",
    "category": "Intermediate",
    "difficulty": 5,
    "hint": "ifconfig, ip, route, resolve.conf",
    "tasks": [
      "Show all network interfaces",
      "Show interface eth0 details",
      "Bring interface up",
      "Bring interface down",
      "Add IP address to interface",
      "Remove IP address from interface",
      "Show routing table",
      "Add default gateway",
      "Delete route",
      "Show ARP table",
      "Flush ARP cache",
      "Show DNS configuration",
      "Add DNS server"
    ],
    "flagHash": "e07c7ef6e309a8e468adcc26e0968605393ce39eacabd70af101c657b8d291bc"
  },
  {
    "id": 20,
    "name": "🛡️ Firewall Management",
    "description": "Configure and manage firewall rules",
    "whatYouLearn": "iptables, ufw, and firewall basics",
    "objective": "Master firewall configuration",
    "category": "Intermediate",
    "difficulty": 6,
    "hint": "iptables for advanced, ufw for simple firewall",
    "tasks": [
      "Show current iptables rules",
      "Show NAT table",
      "Allow SSH on port 22",
      "Allow HTTP on port 80",
      "Allow HTTPS on port 443",
      "Block IP address",
      "Block port 25",
      "Enable NAT masquerading",
      "Enable UFW",
      "Allow SSH via UFW",
      "Allow specific port via UFW",
      "Delete rule by number"
    ],
    "flagHash": "bd0b9464b1226ef1548bf0aabefff88700a4c655fe580574e04690e9985e3d7e"
  },
  {
    "id": 21,
    "name": "⚙️ Systemd Mastery",
    "description": "Manage services with systemd",
    "whatYouLearn": "Systemd, services, units, timers, and journal",
    "objective": "Master systemd service management",
    "category": "Advanced",
    "difficulty": 6,
    "hint": "systemctl, journalctl, service units",
    "tasks": [
      "List all running services",
      "List all services (including inactive)",
      "Start a service",
      "Stop a service",
      "Restart a service",
      "Reload service configuration",
      "Enable service at boot",
      "Disable service at boot",
      "Check service status",
      "Show service logs",
      "Show system logs since last boot",
      "Follow journal in real-time",
      "Show service dependencies",
      "Create a new service unit"
    ],
    "flagHash": "761c2f1646472c21a200896074126fb094ef0eadf74f26505a8e50c827bddf9f"
  },
  {
    "id": 22,
    "name": "📦 Package Management",
    "description": "Manage software packages on Linux",
    "whatYouLearn": "apt, dpkg, yum, dnf for package management",
    "objective": "Master package management",
    "category": "Advanced",
    "difficulty": 5,
    "hint": "apt for Debian/Ubuntu, yum for RHEL/CentOS",
    "tasks": [
      "Update package lists",
      "Upgrade all packages",
      "Install a package",
      "Remove a package",
      "Remove package and configuration",
      "Search for package",
      "Show package information",
      "List installed packages",
      "Install .deb package",
      "Show package contents",
      "Check package dependencies",
      "Fix broken dependencies",
      "Download package without install",
      "Clean package cache"
    ],
    "flagHash": "27908ec9631f31ba311d8140fa0bd047d020a273ed3f7a6859892a2a1ca5b003"
  },
  {
    "id": 23,
    "name": "💾 Disk Management",
    "description": "Manage disks, partitions, and filesystems",
    "whatYouLearn": "fdisk, parted, mkfs, mount, and disk utilities",
    "objective": "Master disk and filesystem management",
    "category": "Advanced",
    "difficulty": 6,
    "hint": "fdisk for partitioning, mkfs for filesystem creation",
    "tasks": [
      "List all disks and partitions",
      "List disk usage",
      "Show disk usage of directory",
      "Show disk usage with details",
      "Create filesystem on partition",
      "Mount partition",
      "Unmount partition",
      "Check filesystem",
      "Show mounted filesystems",
      "Show partition table",
      "Create new partition",
      "Format with swap",
      "Enable swap",
      "Show UUIDs of filesystems"
    ],
    "flagHash": "53a3a1ab11c150fed185d4d0681ccef57b39f70336cdff3200329f9102bf44e3"
  },
  {
    "id": 24,
    "name": "📊 LVM Management",
    "description": "Logical Volume Manager operations",
    "whatYouLearn": "PV, VG, LV creation, extension, and snapshot",
    "objective": "Master LVM administration",
    "category": "Advanced",
    "difficulty": 7,
    "hint": "pvcreate, vgcreate, lvcreate for LVM",
    "tasks": [
      "Show physical volumes",
      "Create physical volume",
      "Show volume groups",
      "Create volume group",
      "Show logical volumes",
      "Create logical volume",
      "Extend logical volume",
      "Reduce logical volume",
      "Create LVM snapshot",
      "Show LVM info",
      "Add disk to volume group",
      "Remove disk from volume group",
      "Activate all LVM volumes",
      "Deactivate all LVM volumes"
    ],
    "flagHash": "6ee4ee492b48f14e938d747e84ac6220df482f44b87404546cd5a30c9748d0f2"
  },
  {
    "id": 25,
    "name": "🔄 RAID Configuration",
    "description": "Configure and manage software RAID",
    "whatYouLearn": "RAID levels, mdadm, and software RAID management",
    "objective": "Master software RAID administration",
    "category": "Advanced",
    "difficulty": 7,
    "hint": "mdadm for software RAID management",
    "tasks": [
      "Create RAID 0 array",
      "Create RAID 1 array",
      "Create RAID 5 array",
      "Show RAID status",
      "List all RAID arrays",
      "Add disk to RAID",
      "Remove disk from RAID",
      "Fail a disk in RAID",
      "Stop RAID array",
      "Assemble RAID array",
      "Save RAID configuration"
    ],
    "flagHash": "3a361051b9969d5369bd9b67cd5301262a4f67561642f780cdfec23db0359795"
  },
  {
    "id": 26,
    "name": "🔑 SSH & Remote Access",
    "description": "Secure Shell configuration and usage",
    "whatYouLearn": "SSH client, server configuration, key management, tunneling",
    "objective": "Master SSH for remote access",
    "category": "Advanced",
    "difficulty": 6,
    "hint": "ssh, sshd_config, ssh-keygen",
    "tasks": [
      "Connect to remote server",
      "Connect on custom port",
      "Generate SSH key pair",
      "Copy SSH key to server",
      "Disable password authentication",
      "Disable root login",
      "Change SSH default port",
      "Create SSH config for host",
      "Set up SSH tunneling",
      "Set up SOCKS proxy",
      "Copy file via SSH",
      "Mount remote directory via SSH",
      "Restart SSH service",
      "Show SSH connection status"
    ],
    "flagHash": "f68b920291ecb2454bce515c107c3c9e06810d2c36fd9111005cd36194ae7353"
  },
  {
    "id": 27,
    "name": "🌐 Web Server Administration",
    "description": "Configure and manage web servers",
    "whatYouLearn": "Apache/Nginx configuration, virtual hosts, SSL/TLS",
    "objective": "Master web server administration",
    "category": "Advanced",
    "difficulty": 7,
    "hint": "a2ensite, a2dissite, nginx configuration",
    "tasks": [
      "Install Apache web server",
      "Start Apache service",
      "Check Apache status",
      "Enable Apache module",
      "Create virtual host",
      "Disable default site",
      "Reload Apache configuration",
      "Install Nginx",
      "Test Nginx configuration",
      "Create SSL certificate",
      "Enable HTTPS in Apache",
      "Set up reverse proxy",
      "Configure load balancing",
      "Set up Gzip compression"
    ],
    "flagHash": "1371a56de1218b2eab977469de2c7b15db1a274e4ed92292816d5b506e54b9bc"
  },
  {
    "id": 28,
    "name": "💾 Database Administration",
    "description": "Manage MySQL/PostgreSQL databases",
    "whatYouLearn": "Database creation, backup, restore, user management",
    "objective": "Master database administration",
    "category": "Advanced",
    "difficulty": 7,
    "hint": "mysql, mysqldump, psql, createdb",
    "tasks": [
      "Install MySQL server",
      "Connect to MySQL",
      "Show all databases",
      "Create new database",
      "Create MySQL user",
      "Grant privileges",
      "Import SQL file",
      "Export database",
      "Install PostgreSQL",
      "Connect to PostgreSQL",
      "Create PostgreSQL database",
      "List PostgreSQL databases",
      "Create PostgreSQL user",
      "Import PostgreSQL dump"
    ],
    "flagHash": "a51af2aeb35d01d4e3bcbd779cba2b3f0feb5d422ff1b072c8f53fb4d525c137"
  },
  {
    "id": 29,
    "name": "📜 Shell Scripting Basics",
    "description": "Create and run shell scripts",
    "whatYouLearn": "Variables, conditionals, loops, functions in bash",
    "objective": "Master basic shell scripting",
    "category": "Advanced",
    "difficulty": 6,
    "hint": "#!/bin/bash, variables, if statements, for loops",
    "tasks": [
      "Create hello world script",
      "Make script executable",
      "Create script with variables",
      "Use if-else in script",
      "Create for loop in script",
      "Use while loop",
      "Create function in script",
      "Use case statement",
      "Create script with arguments",
      "Use arrays in script",
      "Add error handling",
      "Read user input in script"
    ],
    "flagHash": "752722655ef5f7d81969ad01e36faec6ea683addf5a3a83dc2aedfd21c42599a"
  },
  {
    "id": 30,
    "name": "🚀 Advanced Scripting",
    "description": "Advanced shell scripting techniques",
    "whatYouLearn": "Regular expressions, sed, awk, xargs, parallel processing",
    "objective": "Master advanced scripting",
    "category": "Advanced",
    "difficulty": 7,
    "hint": "sed for streaming, awk for data processing",
    "tasks": [
      "Use sed to replace in file",
      "Use sed to delete lines",
      "Use awk to print specific columns",
      "Use awk with conditions",
      "Use xargs to process output",
      "Use xargs with multiple arguments",
      "Use parallel processing",
      "Use grep with regex",
      "Use cut to extract fields",
      "Combine multiple commands",
      "Use here document",
      "Use trap for signals"
    ],
    "flagHash": "0f219260f924630c41aa41dce5f76bcd3c51aae0dcd08ecf88b15eb3413638cd"
  },
  {
    "id": 31,
    "name": "📡 DNS & Bind",
    "description": "Configure and manage DNS server",
    "whatYouLearn": "BIND configuration, zone files, DNS records",
    "objective": "Master DNS server administration",
    "category": "Expert",
    "difficulty": 8,
    "hint": "named, zone files, dig, nslookup",
    "tasks": [
      "Install BIND DNS server",
      "Start BIND service",
      "Check BIND status",
      "Query DNS server",
      "Lookup domain",
      "Create zone file",
      "Add A record",
      "Add CNAME record",
      "Add MX record",
      "Add reverse record",
      "Test configuration",
      "Reload BIND configuration",
      "Enable recursion",
      "Set up DNS forwarding"
    ],
    "flagHash": "966b8dcd60873332c1659ef993cfa2030e83e5b5a47b0df125d8faebbd8c5994"
  },
  {
    "id": 32,
    "name": "🔄 DHCP Server",
    "description": "Configure DHCP server for IP allocation",
    "whatYouLearn": "DHCP configuration, subnetting, IP address management",
    "objective": "Master DHCP server administration",
    "category": "Expert",
    "difficulty": 7,
    "hint": "isc-dhcp-server, dhcpd.conf",
    "tasks": [
      "Install DHCP server",
      "Configure DHCP pool",
      "Set DNS servers in DHCP",
      "Set default gateway",
      "Set domain name",
      "Create DHCP reservation",
      "Set DHCP lease time",
      "Set max lease time",
      "Start DHCP service",
      "Check DHCP status",
      "View DHCP leases",
      "Restart DHCP service",
      "Enable DHCP at boot"
    ],
    "flagHash": "8694b46f183be74f8f62f396468c0ed25bdf6153879d5fa5508f2d8411a7f73c"
  },
  {
    "id": 33,
    "name": "📁 File Sharing",
    "description": "Configure NFS and Samba file sharing",
    "whatYouLearn": "NFS exports, Samba configuration, file sharing protocols",
    "objective": "Master file sharing administration",
    "category": "Expert",
    "difficulty": 7,
    "hint": "exports, smb.conf, mount, smbclient",
    "tasks": [
      "Install NFS server",
      "Create NFS export",
      "Export NFS shares",
      "Show NFS exports",
      "Mount NFS share",
      "Install Samba server",
      "Create Samba share",
      "Add Samba user",
      "Restart Samba service",
      "Check Samba status",
      "List Samba shares",
      "Mount Samba share",
      "Test Samba configuration",
      "Set NFS with no_root_squash"
    ],
    "flagHash": "07a7f7c0bd6d9a2aefd1b44377a960707cf15d14181c745f38bbd89cb803e2e2"
  },
  {
    "id": 34,
    "name": "💾 Backup & Recovery",
    "description": "Backup strategies and system recovery",
    "whatYouLearn": "rsync, tar, dd, system backup and restore",
    "objective": "Master backup and recovery",
    "category": "Expert",
    "difficulty": 7,
    "hint": "rsync, tar, dd, restore commands",
    "tasks": [
      "Create full system backup with tar",
      "Backup home directory",
      "Incremental backup with rsync",
      "Remote backup with rsync",
      "Create disk image with dd",
      "Restore disk image",
      "Create compressed backup",
      "Split large backup into parts",
      "Verify backup integrity",
      "Create backup with exclusions",
      "Create system snapshot",
      "Create bootable backup",
      "Backup configuration files",
      "Recover specific file from backup"
    ],
    "flagHash": "e431e85100f90b556b659636ac98497ca2e0c34bd204fd8258bf90bf7170066c"
  },
  {
    "id": 35,
    "name": "🐳 Docker Introduction",
    "description": "Getting started with containers",
    "whatYouLearn": "Docker installation, images, containers, basic commands",
    "objective": "Master Docker basics",
    "category": "Expert",
    "difficulty": 8,
    "hint": "docker run, ps, images, pull, exec",
    "tasks": [
      "Check Docker version",
      "Pull Ubuntu image",
      "List all images",
      "Run container interactively",
      "Run container in background",
      "List running containers",
      "List all containers",
      "Stop a container",
      "Start a stopped container",
      "Remove a container",
      "Remove an image",
      "Execute command in running container",
      "View container logs",
      "Inspect container details"
    ],
    "flagHash": "073b4bb47233a966cefb199db74f7ee913dc2199d8541718f1ff52814a8376d1"
  },
  {
    "id": 36,
    "name": "🐳 Advanced Docker",
    "description": "Advanced container management",
    "whatYouLearn": "Dockerfile, volumes, networks, docker-compose",
    "objective": "Master advanced Docker concepts",
    "category": "Expert",
    "difficulty": 8,
    "hint": "Dockerfile, volumes, networks, compose",
    "tasks": [
      "Create Dockerfile",
      "Build Docker image",
      "Create volume",
      "List volumes",
      "Run container with volume",
      "Create network",
      "List networks",
      "Run container with network",
      "Create docker-compose.yml",
      "Start with compose",
      "Stop with compose",
      "Scale service",
      "Push image to registry",
      "Save image to file"
    ],
    "flagHash": "6822c918e3cdf93f07d3118380e2f8460a3ba0e5108266665c326e0b2426e023"
  },
  {
    "id": 37,
    "name": "☸️ Kubernetes Introduction",
    "description": "Getting started with Kubernetes",
    "whatYouLearn": "kubectl commands, pods, services, deployments",
    "objective": "Master Kubernetes basics",
    "category": "Expert",
    "difficulty": 9,
    "hint": "kubectl get, apply, describe, logs",
    "tasks": [
      "Check kubectl version",
      "List nodes",
      "List all pods",
      "Create deployment",
      "List deployments",
      "Scale deployment",
      "Expose deployment as service",
      "List services",
      "Get pod details",
      "View pod logs",
      "Execute command in pod",
      "Delete deployment",
      "Apply YAML configuration",
      "Port forward to service"
    ],
    "flagHash": "c5a84036c25d02166259efc6a47ffe229fafab38c12b482a2196a28dc2c0bb75"
  },
  {
    "id": 38,
    "name": "☸️ Advanced Kubernetes",
    "description": "Advanced Kubernetes operations",
    "whatYouLearn": "ConfigMaps, Secrets, Ingress, Persistent Volumes, Helm",
    "objective": "Master advanced Kubernetes",
    "category": "Expert",
    "difficulty": 9,
    "hint": "configmap, secret, ingress, pv, pvc, helm",
    "tasks": [
      "Create ConfigMap",
      "List ConfigMaps",
      "Create Secret",
      "List Secrets",
      "Create PersistentVolume",
      "Create PersistentVolumeClaim",
      "Create Ingress resource",
      "Install Helm",
      "Add Helm repo",
      "Install chart with Helm",
      "List Helm releases",
      "Upgrade Helm release",
      "Uninstall Helm release"
    ],
    "flagHash": "f62378bc3a86c4e661ac20c59480f71be918c3c4c9f5356d73958e19e4f391e1"
  },
  {
    "id": 39,
    "name": "🚀 CI/CD Pipeline",
    "description": "Continuous Integration and Deployment",
    "whatYouLearn": "Jenkins, GitLab CI, GitHub Actions, pipeline automation",
    "objective": "Master CI/CD pipeline creation",
    "category": "Expert",
    "difficulty": 9,
    "hint": "jenkins, gitlab-ci.yml, github actions",
    "tasks": [
      "Install Jenkins",
      "Start Jenkins service",
      "Check Jenkins status",
      "Create Jenkins pipeline",
      "Create GitLab CI pipeline",
      "Create GitHub Actions workflow",
      "Add test stage",
      "Add deploy stage",
      "Build Docker image in CI",
      "Push image to registry",
      "Deploy to Kubernetes",
      "View Jenkins logs",
      "List Jenkins jobs",
      "Create multi-stage pipeline"
    ],
    "flagHash": "c485ea41ffd8d9acec7b2c15b243689b5cde4641ad42011547538ac1b2ffc18b"
  },
  {
    "id": 40,
    "name": "☁️ Cloud CLI Mastery",
    "description": "Manage cloud resources from command line",
    "whatYouLearn": "AWS CLI, GCP gcloud, Azure CLI commands",
    "objective": "Master cloud CLI tools",
    "category": "Expert",
    "difficulty": 9,
    "hint": "aws, gcloud, az commands",
    "tasks": [
      "Install AWS CLI",
      "Configure AWS CLI",
      "List EC2 instances",
      "Create S3 bucket",
      "List S3 buckets",
      "Sync to S3",
      "Install GCP gcloud",
      "Authenticate to GCP",
      "List GCP instances",
      "Create GCP VM",
      "Install Azure CLI",
      "Login to Azure",
      "List Azure VMs",
      "Create Azure VM"
    ],
    "flagHash": "0ba0ac2b318caaf4ed11549bd986dfc6ac2cdec5ab9b23327c5420bfb3a389db"
  },
  {
    "id": 41,
    "name": "🏗️ Infrastructure as Code",
    "description": "Manage infrastructure with code",
    "whatYouLearn": "Terraform, Ansible, CloudFormation basics",
    "objective": "Master IaC tools",
    "category": "Master",
    "difficulty": 9,
    "hint": "terraform, ansible, cloudformation",
    "tasks": [
      "Install Terraform",
      "Initialize Terraform",
      "Create Terraform plan",
      "Plan Terraform changes",
      "Apply Terraform changes",
      "Destroy Terraform resources",
      "Install Ansible",
      "Create Ansible inventory",
      "Create Ansible playbook",
      "Run Ansible playbook",
      "Test Ansible connection",
      "Create AWS CloudFormation",
      "Create CloudFormation stack",
      "Delete CloudFormation stack"
    ],
    "flagHash": "7bac2c640a02de4f39bcb1a2ec160c8c3f0db68717c4f3f9686932cea1c45c6a"
  },
  {
    "id": 42,
    "name": "📊 Monitoring & Alerting",
    "description": "Set up monitoring and alerting systems",
    "whatYouLearn": "Prometheus, Grafana, Nagios, Alertmanager",
    "objective": "Master monitoring and alerting",
    "category": "Master",
    "difficulty": 8,
    "hint": "prometheus, grafana, nagios, alerts",
    "tasks": [
      "Download Prometheus",
      "Extract Prometheus",
      "Start Prometheus",
      "Check Prometheus status",
      "Install Grafana",
      "Start Grafana",
      "Check Grafana status",
      "Add Prometheus data source",
      "Install Nagios",
      "Create Nagios check",
      "Install Alertmanager",
      "Create alert rule",
      "Configure Grafana dashboard",
      "Set up Slack alerts"
    ],
    "flagHash": "3f6c33ed4ae000c1b3f4bceb035ac0d7da903f46182b5935af9de332603136a6"
  },
  {
    "id": 43,
    "name": "📝 Logging & ELK Stack",
    "description": "Centralized logging with ELK Stack",
    "whatYouLearn": "Elasticsearch, Logstash, Kibana, Filebeat",
    "objective": "Master ELK Stack for logging",
    "category": "Master",
    "difficulty": 9,
    "hint": "elasticsearch, logstash, kibana, filebeat",
    "tasks": [
      "Install Elasticsearch",
      "Start Elasticsearch",
      "Check Elasticsearch status",
      "Install Kibana",
      "Start Kibana",
      "Install Logstash",
      "Create Logstash pipeline",
      "Start Logstash",
      "Install Filebeat",
      "Configure Filebeat",
      "Start Filebeat",
      "Create Elasticsearch index",
      "Query Elasticsearch",
      "Create Kibana dashboard"
    ],
    "flagHash": "56874f612e2f511367abdbe20ca773153a61203538c93dfc620e12bc3829b6bf"
  },
  {
    "id": 44,
    "name": "🛡️ Security Hardening",
    "description": "Harden Linux system security",
    "whatYouLearn": "Security best practices, auditing, SELinux, AppArmor",
    "objective": "Master system security hardening",
    "category": "Master",
    "difficulty": 9,
    "hint": "auditd, SELinux, AppArmor, fail2ban",
    "tasks": [
      "Enable SELinux",
      "Check SELinux status",
      "Install AppArmor",
      "Enable AppArmor",
      "Install fail2ban",
      "Start fail2ban",
      "Configure fail2ban for SSH",
      "Install auditd",
      "Create audit rule",
      "List audit rules",
      "Check failed login attempts",
      "Configure password policy",
      "Disable unused services",
      "Set up security updates"
    ],
    "flagHash": "ab9c3aee7999b0a55bba0548f98a9cd7911f1fddadfabfc887cc60b52f4576c5"
  },
  {
    "id": 45,
    "name": "⚡ Performance Tuning",
    "description": "Optimize system performance",
    "whatYouLearn": "Kernel tuning, sysctl, performance analysis",
    "objective": "Master system performance tuning",
    "category": "Master",
    "difficulty": 10,
    "hint": "sysctl, kernel parameters, performance tools",
    "tasks": [
      "Show all sysctl parameters",
      "Optimize TCP parameters",
      "Increase file descriptors",
      "Optimize swappiness",
      "Increase TCP buffer",
      "Optimize TCP congestion",
      "Show CPU performance",
      "Set CPU governor",
      "Check I/O scheduler",
      "Set I/O scheduler",
      "Analyze system with perf",
      "Use strace for debugging",
      "Check process limits",
      "Optimize kernel parameters"
    ],
    "flagHash": "e08de54346b8319e84258b2126e79ca56887ca974ee900c88b3cc58b7e7dc161"
  },
  {
    "id": 46,
    "name": "🌐 Advanced Networking",
    "description": "Advanced network configuration",
    "whatYouLearn": "VLANs, bonding, bridging, routing, network namespaces",
    "objective": "Master advanced networking",
    "category": "Master",
    "difficulty": 10,
    "hint": "vlan, bond, bridge, network namespaces",
    "tasks": [
      "Create VLAN interface",
      "Create bond interface",
      "Add interfaces to bond",
      "Create bridge interface",
      "Add interface to bridge",
      "Create network namespace",
      "List network namespaces",
      "Execute command in namespace",
      "Create veth pair",
      "Move veth to namespace",
      "Configure BGP routing",
      "Setup policy routing",
      "Create network policy",
      "Configure QoS"
    ],
    "flagHash": "14ae7ba10bbd29d0f277b152a190d6552f81ed1d9bf23f7024961edc477bbcb2"
  },
  {
    "id": 47,
    "name": "🖥️ Virtualization",
    "description": "Manage virtual machines with KVM/QEMU",
    "whatYouLearn": "KVM, QEMU, libvirt, virsh commands",
    "objective": "Master virtualization",
    "category": "Master",
    "difficulty": 10,
    "hint": "virsh, virt-install, qemu, libvirt",
    "tasks": [
      "Check KVM support",
      "Install KVM packages",
      "Start libvirtd service",
      "Check libvirtd status",
      "List virtual networks",
      "Create VM with virt-install",
      "List all VMs",
      "Start VM",
      "Stop VM",
      "Delete VM",
      "Create VM snapshot",
      "List VM snapshots",
      "Connect to VM console",
      "Show VM info"
    ],
    "flagHash": "9d7e6fe46c83e350bcfd28184ddfe41ce36bed2b73d00292621536ffc8625f9c"
  },
  {
    "id": 48,
    "name": "🤖 Automation Master",
    "description": "Infrastructure automation",
    "whatYouLearn": "Ansible, Puppet, Chef, configuration management",
    "objective": "Master automation tools",
    "category": "Master",
    "difficulty": 10,
    "hint": "ansible-playbook, puppet apply, chef-solo",
    "tasks": [
      "Install Ansible",
      "Create Ansible inventory",
      "Create Ansible playbook",
      "Run Ansible playbook",
      "Install Puppet",
      "Create Puppet manifest",
      "Apply Puppet manifest",
      "Install Chef",
      "Create Chef recipe",
      "Run Chef recipe",
      "Create Ansible role",
      "Use Ansible vault",
      "List Ansible modules",
      "Create Ansible dynamic inventory"
    ],
    "flagHash": "2390ec40a71d9e7aea8de3289b26d44509cffde44c398819a7da1dfd17c932c0"
  },
  {
    "id": 49,
    "name": "🔄 High Availability",
    "description": "Configure high availability systems",
    "whatYouLearn": "Pacemaker, Corosync, HAProxy, load balancing",
    "objective": "Master high availability",
    "category": "Master",
    "difficulty": 10,
    "hint": "pacemaker, corosync, haproxy, keepalived",
    "tasks": [
      "Install HAProxy",
      "Configure HAProxy",
      "Start HAProxy",
      "Install Keepalived",
      "Configure Keepalived",
      "Start Keepalived",
      "Install Pacemaker",
      "Start Pacemaker",
      "Configure Corosync",
      "Create cluster resource",
      "Add cluster constraint",
      "Set up DRBD",
      "Check cluster status",
      "Configure load balancer"
    ],
    "flagHash": "7295ca17b52ff58d97464ec3dbc6b9e2ad2f98d89de592d792f7caaf0eb4b85f"
  },
  {
    "id": 50,
    "name": "🏆 Ultimate Linux Master",
    "description": "The final challenge - everything combined",
    "whatYouLearn": "All Linux skills combined - the ultimate test",
    "objective": "Complete the ultimate Linux mastery challenge",
    "category": "Master",
    "difficulty": 10,
    "hint": "Use every skill you've learned!",
    "tasks": [
      "Check system information",
      "Check network configuration",
      "Check running services",
      "Find all files modified in last 24 hours",
      "Check system logs for errors",
      "Create and run a bash script",
      "Check process status",
      "Check disk usage",
      "Check network connections",
      "Check system load",
      "Check security status",
      "Check docker containers",
      "Check Kubernetes pods",
      "Check cloud resources",
      "Create backup",
      "Check system performance",
      "Check network performance",
      "Find the final flag"
    ],
    "flagHash": "51a0cf220c1d5e161729ab81334ea6b263e81917a46adeaff6e30eae4fe6d11e"
  }
];
